-- Populate Wordle database with sample data
-- Run this script in your Supabase SQL Editor

-- First, check if wordle table exists and what data is already there
SELECT COUNT(*) as current_count FROM wordle;

-- Insert sample Wordle data for the past week and upcoming days
INSERT INTO wordle (date, word, definition, interesting_fact) VALUES
  ('2025-09-23', 'TOAST', 'Sliced bread browned by exposure to radiant heat.', 'The word "toast" comes from the Latin "torrere," meaning "to parch." The French "toster" evolved into our modern word.'),
  ('2025-09-24', 'PLANT', 'A living organism that grows in the earth and has a stem, leaves, and roots.', 'Plants produce oxygen through photosynthesis, generating about 330 billion tons of oxygen annually - enough for all life on Earth.'),
  ('2025-09-25', 'MUSIC', 'Vocal or instrumental sounds combined in such a way as to produce beauty of form, harmony, and expression of emotion.', 'The word "music" derives from the Greek "mousike," meaning "art of the Muses" - the nine goddesses who inspired the arts.'),
  ('2025-09-26', 'CRANE', 'A large, tall machine used for moving heavy objects by suspending them from a projecting arm.', 'Construction cranes are named after the bird because their silhouette resembles a crane''s long neck and beak when extended.'),
  ('2025-09-27', 'FLAME', 'A hot glowing body of ignited gas that is generated by something on fire.', 'The blue part of a flame is actually the hottest, reaching temperatures up to 3,000°F (1,650°C), hotter than the yellow part.'),
  ('2025-09-28', 'PROUD', 'Feeling deep pleasure or satisfaction as a result of one''s own achievements.', 'The phrase "proud as a peacock" comes from the bird''s elaborate tail display, used to attract mates and show dominance.'),
  ('2025-09-29', 'SWIFT', 'Happening quickly or promptly; moving or capable of moving with great speed.', 'Swift birds can reach speeds over 100 mph in a dive, making them among the fastest creatures in the animal kingdom.'),
  ('2025-09-30', 'BEACH', 'A pebbly or sandy shore, especially by the ocean between high- and low-water marks.', 'The word "beach" originally meant "pebbles" in Old English, from the word "bæce" meaning stone or boulder.'),
  ('2025-10-01', 'LIGHT', 'The natural agent that stimulates sight and makes things visible.', 'Light travels at 299,792,458 meters per second in a vacuum - so fast it could circle Earth 7.5 times in just one second.'),
  ('2025-10-02', 'QUEST', 'A long or arduous search for something.', 'The word "quest" comes from the Latin "quaerere," meaning "to ask" or "to seek," the same root as "question."')
ON CONFLICT (date) DO NOTHING;

-- Check final count
SELECT COUNT(*) as final_count FROM wordle;

-- Show recent entries
SELECT date, word, LEFT(definition, 50) || '...' as definition_preview
FROM wordle
ORDER BY date DESC
LIMIT 10;