import { NextRequest, NextResponse } from 'next/server'
import { validateDebugAuth } from '@/lib/debug-auth'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { supabaseAdmin } from '@/lib/supabase'

export async function POST(request: any) {
  // Validate authentication
  const authResult = validateDebugAuth(request)
  if (!authResult.authorized) {
    return authResult.response
  }

  try {
    const session = await getServerSession(authOptions)
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()
    const { days = 7 } = body // Default to populate 7 days

    console.log(`Populating Wordle database with ${days} days of sample data...`)

    // Sample Wordle data for testing
    const sampleWordles = [
      {
        date: '2025-09-23',
        word: 'TOAST',
        definition: 'Sliced bread browned by exposure to radiant heat.',
        interesting_fact: 'The word "toast" comes from the Latin "torrere," meaning "to parch." The French "toster" evolved into our modern word.'
      },
      {
        date: '2025-09-24',
        word: 'PLANT',
        definition: 'A living organism that grows in the earth and has a stem, leaves, and roots.',
        interesting_fact: 'Plants produce oxygen through photosynthesis, generating about 330 billion tons of oxygen annually - enough for all life on Earth.'
      },
      {
        date: '2025-09-25',
        word: 'MUSIC',
        definition: 'Vocal or instrumental sounds combined in such a way as to produce beauty of form, harmony, and expression of emotion.',
        interesting_fact: 'The word "music" derives from the Greek "mousike," meaning "art of the Muses" - the nine goddesses who inspired the arts.'
      },
      {
        date: '2025-09-26',
        word: 'CRANE',
        definition: 'A large, tall machine used for moving heavy objects by suspending them from a projecting arm.',
        interesting_fact: 'Construction cranes are named after the bird because their silhouette resembles a crane\'s long neck and beak when extended.'
      },
      {
        date: '2025-09-27',
        word: 'FLAME',
        definition: 'A hot glowing body of ignited gas that is generated by something on fire.',
        interesting_fact: 'The blue part of a flame is actually the hottest, reaching temperatures up to 3,000°F (1,650°C), hotter than the yellow part.'
      },
      {
        date: '2025-09-28',
        word: 'PROUD',
        definition: 'Feeling deep pleasure or satisfaction as a result of one\'s own achievements.',
        interesting_fact: 'The phrase "proud as a peacock" comes from the bird\'s elaborate tail display, used to attract mates and show dominance.'
      },
      {
        date: '2025-09-29',
        word: 'SWIFT',
        definition: 'Happening quickly or promptly; moving or capable of moving with great speed.',
        interesting_fact: 'Swift birds can reach speeds over 100 mph in a dive, making them among the fastest creatures in the animal kingdom.'
      }
    ]

    let insertedCount = 0
    let skippedCount = 0

    for (let i = 0; i < Math.min(days, sampleWordles.length); i++) {
      const wordleData = sampleWordles[i]

      // Check if entry already exists
      const { data: existing } = await supabaseAdmin
        .from('wordle')
        .select('id')
        .eq('date', wordleData.date)
        .single()

      if (existing) {
        console.log(`Wordle for ${wordleData.date} already exists, skipping`)
        skippedCount++
        continue
      }

      // Insert new Wordle entry
      const { error } = await supabaseAdmin
        .from('wordle')
        .insert([wordleData])

      if (error) {
        console.error(`Error inserting Wordle for ${wordleData.date}:`, error)
        throw error
      }

      console.log(`Inserted Wordle for ${wordleData.date}: ${wordleData.word}`)
      insertedCount++
    }

    // Get final count
    const { data: allWordles, error: countError } = await supabaseAdmin
      .from('wordle')
      .select('date, word')
      .order('date', { ascending: false })
      .limit(10)

    return NextResponse.json({
      success: true,
      message: `Wordle population completed`,
      inserted: insertedCount,
      skipped: skippedCount,
      total_in_db: allWordles?.length || 0,
      recent_entries: allWordles || []
    })

  } catch (error) {
    console.error('Wordle population error:', error)
    return NextResponse.json({
      error: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 })
  }
}